ConvertToTxt()
{
  file=$1
  
  [[ "$verbose" = "y" ]] && echo "Converting $file to txt..."
  sed -i 's/\[em\]//g'         "$file"
  sed -i 's/\[\/em\]//g'       "$file"
  sed -i 's/\[b\]//g'          "$file"
  sed -i 's/\[\/b\]//g'        "$file"
  sed -i 's/\[u\]//g'          "$file"
  sed -i 's/\[\/u\]//g'        "$file"
  sed -i 's/\[s\]//g'          "$file"
  sed -i 's/\[\/s\]//g'        "$file"
  sed -i 's/\[i\]//g'          "$file"
  sed -i 's/\[\/i\]//g'        "$file"
  sed -i 's/\[sup\]//g'        "$file"
  sed -i 's/\[\/sup\]//g'      "$file"
  sed -i 's/\[sub\]//g'        "$file"
  sed -i 's/\[\/sub\]//g'      "$file"
  sed -i 's/\[center\]//g'     "$file"
  sed -i 's/\[\/center\]//g'   "$file"
  sed -i 's/\[wbr\]//g'        "$file"
  sed -i 's/\[cite\]//g'       "$file"
  sed -i 's/\[\/cite\]//g'     "$file"
  sed -i 's/\[dfn\]//g'        "$file"
  sed -i 's/\[\/dfn\]//g'      "$file"
  sed -i 's/\[el\]/\. \. \./g' "$file"
  sed -i 's/\[a:"//g'          "$file"
  sed -i 's/\[\/a\]//g'        "$file"
  sed -i 's/\[img:"//g'        "$file"
  sed -i 's/\[\/img\]//g'      "$file"
  sed -i 's/"\]//g'            "$file"
  sed -i 's/\[ol\]//g'         "$file"
  sed -i 's/\[\/ol\]//g'       "$file"
  sed -i 's/\[ul\]//g'         "$file"
  sed -i 's/\[\/ul\]//g'       "$file"
  sed -i 's/\[li\]/-/g'        "$file"
  sed -i 's/\[\/li\]//g'       "$file"
  sed -i 's/``/"/g'            "$file"
  sed -i "s/\`/'/g"            "$file"
  sed -i "s/''/\"/g"           "$file"
  [[ "$verbose" = "y" ]] && echo "$file converted to txt."
}
