ConvertToHTML()
{
  file=$1
  
  [[ "$verbose" = "y" ]] && echo "Converting $file to HTML..."
  sed -i 's/\[em\]/<em>/g'                      "$file"
  sed -i 's/\[\/em\]/<\/em>/g'                  "$file"
  sed -i 's/\[b\]/<strong>/g'                   "$file"
  sed -i 's/\[\/b\]/<\/strong>/g'               "$file"
  sed -i 's/\[u\]/<u>/g'                        "$file"
  sed -i 's/\[\/u\]/<\/u>/g'                    "$file"
  sed -i 's/\[s\]/<s>/g'                        "$file"
  sed -i 's/\[\/s\]/<\/s>/g'                    "$file"
  sed -i 's/\[i\]/<i>/g'                        "$file"
  sed -i 's/\[\/i\]/<\/i>/g'                    "$file"
  sed -i 's/\[sup\]/<sup>/g'                    "$file"
  sed -i 's/\[\/sup\]/<\/sup>/g'                "$file"
  sed -i 's/\[sub\]/<sub>/g'                    "$file"
  sed -i 's/\[\/sub\]/<\/sub>/g'                "$file"
  sed -i 's/\[center\]/<span class="center">/g' "$file"
  sed -i 's/\[\/center\]/<\/span>/g'            "$file"
  sed -i 's/\[wbr\]/<wbr>/g'                    "$file"
  sed -i 's/\[cite\]/<cite>/g'                  "$file"
  sed -i 's/\[\/cite\]/<\/cite>/g'              "$file"
  sed -i 's/\[dfn\]/<dfn>/g'                    "$file"
  sed -i 's/\[\/dfn\]/<\/dfn>/g'                "$file"
  sed -i "s/' '/'\&thinsp;'/g"                  "$file"
  sed -i 's/` `/`\&thinsp;`/g'                  "$file"
  sed -i 's/``/\&ldquo;/g'                      "$file"
  sed -i 's/`/\&lsquo;/g'                       "$file"
  sed -i "s/''/\&rdquo;/g"                      "$file"
  sed -i "s/'/\&rsquo;/g"                       "$file"
  sed -i 's/---/\&#x200b;\&mdash;\&#x200b;/g'   "$file"
  sed -i 's/--/\&#x200b;\&ndash;\&#x200b;/g'    "$file"
  sed -i 's/\[el\]/\&hellip;/g'                 "$file"
  sed -i 's/\[a:"/<a href="/g'                  "$file"
  sed -i 's/\[\/a\]/<\/a>/g'                    "$file"
  sed -i 's/\[img:"/<img src="/g'               "$file"
  sed -i 's/\[\/img\]/<\/img>/g'                "$file"
  sed -i 's/"\]/">/g'                           "$file"
  sed -i 's/^/<p>/'                             "$file"
  sed -i 's/$/<\/p>/'                           "$file"
  sed -i 's/<p> *\[ol\]<\/p>/<ol>/g'            "$file"
  sed -i 's/<p> *\[\/ol\]<\/p>/<\/ol>/g'        "$file"
  sed -i 's/<p> *\[ul\]<\/p>/<ul>/g'            "$file"
  sed -i 's/<p> *\[\/ul\]<\/p>/<\/ul>/g'        "$file"
  sed -i 's/<p> *\[li\]/<li>/g'                 "$file"
  sed -i 's/\[\/li\]<\/p>/<\/li>/g'             "$file"
  sed -i '/^<p><\/p>$/d'                        "$file"
  [[ "$verbose" = "y" ]] && echo "$file converted to HTML."
}
